### ISSUE TITLE
 Error: There is no package called ‘DESeq2’

### ISSUE THREAD

**Issue by fbbjn** [sjroth/ARTDeco#10]
Hello, 

I am trying to run ARTDeco on my RNAseq data and I keep getting this error.
I tried to re-install DESeq2 and other packages but nothing changes
Any idea why?

Thanks for your help

```
(ARTDeco) fbbjn@IC-7183:/mnt/f/ARTDeco$ ARTDeco -mode preprocess -gtf-file /mnt/f/pipe_kevin/RS-pipe/pipeline_rna/ref/gencode.v37.annotation.gtf -chrom-sizes-file hg38.chrom.sizes -meta-file meta_P7.txt -bam-files-dir /mnt/f/pipe_kevin/RS-pipe/pipeline_rna/sorted_bam -readthrough-dist 1 -intergenic-min-len 5 -intergenic-max-len 15
Running preprocess mode...
Loading ARTDeco file structure...
/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version. The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
R[write to console]: Error in loadNamespace(name) : there is no package called ‘DESeq2’

Traceback (most recent call last):
  File "/home/fbbjn/anaconda3/envs/ARTDeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/ARTDeco-0.4-py3.8.egg/ARTDeco/main.py", line 115, in main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/ARTDeco-0.4-py3.8.egg/ARTDeco/DESeq2.py", line 12, in <module>
  File "/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/rpy2/robjects/packages.py", line 477, in importr
    env = _get_namespace(rname)
  File "/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/home/fbbjn/anaconda3/envs/ARTDeco/lib/python3.8/site-packages/rpy2/rinterface.py", line 785, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in loadNamespace(name) : there is no package called ‘DESeq2’

```

**Comment by sjroth** [comment]
Did you install the Conda environment provided in the repo? It does not look like you did as the python version should be 3.6.

**Comment by fbbjn** [comment]
Even when I try to install the required packages in a Python 3.6 environment, i keep getting errors


```
(py36) fbbjn@IC-7183:/mnt/f/ARTDeco$ conda install bedops=2.4.* bioconductor-deseq2=1.20.* bx-python=0.8.* homer=4.9.* networkx=2.* numpy=1.16.* pandas=0.24.* pybigwig rpy2=2.9.* rseqc=3.0.* samtools=1.9 -n py36
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pybigwig
  - samtools=1.9
  - homer=4.9
  - bedops=2.4
  - rseqc=3.0
  - bx-python=0.8
  - bioconductor-deseq2=1.20

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by sjroth** [comment]
There are several problems here. 
1. You did not try to install python 3.6. You need to include python=3.6.* in your install command if you are going that direction.
2. You need to install the bioconda channel on anaconda.
3. To avoid these issues, please use the environment.yml file provided in the repo. That is the best way to avoid these versioning issues.

**Comment by sjroth** [comment]
Closing this issue as there has been no response.

**Comment by sjroth** [comment]
Closing this issue as there has been no response.
