### ISSUE TITLE
issue with ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by haonanduanmu** [sjroth/ARTDeco#23]
Hi,

I'm using ARTDeco and coming across a question about "ValueError: invalid literal for int() with base 10: b''.

My code is 

> ARTDeco -home-dir ARTDeco_dir/ -bam-files-dir bam_file/ -gtf-file dmel_flybase.gtf -chrom-sizes-file genome.chrom.sizes

and there are 80 bam files which were sorted.
the problem is

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/public1/home/scfa2661/anaconda3/envs/ARTDeco/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/public1/home/scfa2661/anaconda3/envs/ARTDeco/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/public1/home/scfa2661/anaconda3/envs/ARTDeco/lib/python3.9/site-packages/ARTDeco-0.4-py3.9.egg/ARTDeco/misc.py", line 364, in count_reads
>     return int(output.strip())
> ValueError: invalid literal for int() with base 10: b''
> """ 

I have no idea about this bug, maybe the bam files have some wrong? Could you help me?
Thank u!

**Comment by sjroth** [comment]
Hi,

Can you please show all of your stdout rather than just the error?

Sam

**Comment by haonanduanmu** [comment]
Here is the picture of all stdout
 
![1709864267572](https://github.com/sjroth/ARTDeco/assets/102204463/95574475-63bf-4e26-81eb-ade6c04c0be6)

**Comment by sjroth** [comment]
This appears to be an issue with one of your BAM files. One of them is likely not properly formatted.

**Comment by haonanduanmu** [comment]
Is there any method to find this un-formatted bam file? I have tried 'samtools quickcheck' to find this uncorrect file, but it showed that all ok.

**Comment by sjroth** [comment]
Try running "samtools view -c" with whatever other necessary keywords to count the number of reads for each sample. Parsing the output of this command is where the error is occurring.

**Comment by faleevz** [comment]
Hi, having the same problem- have run samtools to check whether all my bam files are formatted correctly and have roughly same amount of reads (which is true). Would be grateful for any further insight? 

```
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5dD_LATE_R1_S3.sort.dedup.bam
20609729
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5dD_LATE_R2_S11.sort.dedup.bam
20323589
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5dP_LATE_R1_S4.sort.dedup.bam
18114441
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5dP_LATE_R2_S12.sort.dedup.bam
30559820
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5ND_LATE_R1_S1.sort.dedup.bam
15258988
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5ND_LATE_R2_S9.sort.dedup.bam
22254209
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5NP_LATE_R1_S2.sort.dedup.bam
20052400
(artdeco) [mfaleeva@papr-res-compute07 bam]$ samtools view -c 5NP_LATE_R2_S10.sort.dedup.bam
1973197
(artdeco) [mfaleeva@papr-res-compute07 bam]$ ARTDeco -home-dir /home/mfaleeva/ARTDeco-master_2 -bam-files-dir /home/mfaleeva/ARTDeco-master_2/bam -layout SE -stranded TRUE -orientation Reverse -gtf-file /home/mfaleeva/ARTDeco-master_2/newgenes.gtf -cpu 8 -chrom-sizes-file /home/mfaleeva/ARTDeco-master_2/genome.chrom.sizes -meta-file /home/mfaleeva/ARTDeco-master_2/meta.txt -comparisons-file /home/mfaleeva/ARTDeco-master_2/comparisons.txt
No valid run mode specified... Will generate all files...
Loading ARTDeco file structure...
Reformatted meta file exists...
Reformatted comparisons file exists...
ARTDeco will generate the following files:
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5dD_LATE_R2_S11.sort.dedup
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs/dD-NP-results.txt
/home/mfaleeva/ARTDeco-master_2/dogs/all_dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5ND_LATE_R1_S1.sort.dedup
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-dP_-read_in_assignment.txt
/home/mfaleeva/ARTDeco-master_2/dogs/._5dD_LATE_R1_S3.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R2_S12.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs/dD-dP-results.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/._5dD_LATE_R1_S3.sort.dedup
/home/mfaleeva/ARTDeco-master_2/readthrough
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R2_S11.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5ND_LATE_R2_S9.sort.dedup
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R2_S11.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/quantification/readthrough.raw.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R2_S11.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R2_S12.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs/ND-NP-results.txt
/home/mfaleeva/ARTDeco-master_2/quantification
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R1_S3.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R1_S1.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R2_S9.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R1_S3.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/dD-dP-read_in.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R2_S10.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/dogs/._5dD_LATE_R1_S3.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5NP_LATE_R2_S10.sort.dedup
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/dD-dP-read_in_assignment.txt
/home/mfaleeva/ARTDeco-master_2/quantification/gene.exp.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R1_S2.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/dD-NP-read_in.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/gene_to_transcript.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-NP-read_in.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-dP_-read_in.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-dD-read_in_assignment.txt
/home/mfaleeva/ARTDeco-master_2/dogs
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5NP_LATE_R1_S2.sort.dedup
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R2_S12.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5dP_LATE_R2_S12.sort.dedup
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs
/home/mfaleeva/ARTDeco-master_2/preprocess_files/read_in.bed
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs/ND-dD-results.txt
/home/mfaleeva/ARTDeco-master_2/dogs/all_dogs.bed
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-dD-read_in.txt
/home/mfaleeva/ARTDeco-master_2/readthrough/corrected_exp.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5dD_LATE_R1_S3.sort.dedup
/home/mfaleeva/ARTDeco-master_2/quantification/max_isoform.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp/ND-dP_-results.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp/ND-dD-results.txt
/home/mfaleeva/ARTDeco-master_2/quantification/read_in.raw.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/dD-NP-read_in_assignment.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/gene_types.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R2_S10.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R1_S4.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_dogs/ND-dP_-results.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp/dD-NP-results.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dD_LATE_R1_S3.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R1_S2.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R1_S4.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/readthrough/readthrough.txt
/home/mfaleeva/ARTDeco-master_2/readthrough/read_in.txt
/home/mfaleeva/ARTDeco-master_2/diff_exp_read_in/ND-NP-read_in_assignment.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R1_S2.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R2_S9.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/diff_exp/ND-NP-results.txt
/home/mfaleeva/ARTDeco-master_2/readthrough/read_in_assignments.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R1_S1.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/preprocess_files/readthrough.bed
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R1_S1.sort.dedup.dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/all_dogs.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/5dP_LATE_R1_S4.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/quantification/gene.exp.fpkm.txt
/home/mfaleeva/ARTDeco-master_2/dogs/._5dD_LATE_R1_S3.sort.dedup.dogs.bed
/home/mfaleeva/ARTDeco-master_2/dogs/5NP_LATE_R2_S10.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/genes_condensed.bed
/home/mfaleeva/ARTDeco-master_2/dogs/5ND_LATE_R2_S9.sort.dedup.dogs.raw.txt
/home/mfaleeva/ARTDeco-master_2/preprocess_files/5dP_LATE_R1_S4.sort.dedup
/home/mfaleeva/ARTDeco-master_2/diff_exp/dD-dP-results.txt
GTF file needed... Checking...
GTF file exists...
BAM file format needed... Checking... Will infer if not user-specified.
BAM files specified as single-end...
BAM files specified as stranded...
BAM files specified as reverse-strand oriented...
Summarizing BAM file stats...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/misc.py", line 364, in count_reads
    return int(output.strip())
ValueError: invalid literal for int() with base 10: b''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mfaleeva/.conda/envs/artdeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/main.py", line 382, in main
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/misc.py", line 376, in summarize_bam_files
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: invalid literal for int() with base 10: b''
```

**Comment by sjroth** [comment]
Inactive for now so closing.
