### ISSUE TITLE
Error in Readthrough: ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat

### ISSUE THREAD

**Issue by faleevz** [sjroth/ARTDeco#25]
Hi there, when running the readthrough mode I keep getting this error. 
```
(artdeco) [mfaleeva@papr-res-compute07 ARTDeco-master_3]$ ARTDeco -mode readthrough -gtf-file /home/mfaleeva/ARTDeco-master_3/newgenes.gtf [-home-dir /home/mfaleeva/ARTDeco-master_3 -bam-files-dir /home/mfaleeva/ARTDeco-master_3/bam -layout SE -stranded TRUE -orientation Reverse -cpu 8 ]
Running readthrough mode...
Loading ARTDeco file structure...
ARTDeco will generate the following files:
./quantification/readthrough.raw.txt
./quantification/max_isoform.txt
./readthrough/readthrough.txt
./quantification/gene.exp.raw.txt
./readthrough/read_in_assignments.txt
./readthrough/corrected_exp.txt
./quantification/gene.exp.fpkm.txt
./readthrough
./readthrough/read_in.txt
./quantification/read_in.raw.txt
GTF file needed... Checking...
GTF file exists...
BAM file format needed... Checking... Will infer if not user-specified.
BAM files specified as single-end...
BAM files specified as stranded...
BAM files specified as reverse-strand oriented...
Summarizing BAM file stats...
8 Experiments
Files are Single-End, Strand-Specific, Reverse-strand oriented
                                                         Experiment  Total Reads  Mapped Reads
 /home/mfaleeva/ARTDeco-master_3/bam/x5NP_LATE_R1_S2.sort.dedup.bam     20052400      20052400
 /home/mfaleeva/ARTDeco-master_3/bam/x5dP_LATE_R1_S4.sort.dedup.bam     18114441      18114441
/home/mfaleeva/ARTDeco-master_3/bam/x5NP_LATE_R2_S10.sort.dedup.bam      1973197       1973197
/home/mfaleeva/ARTDeco-master_3/bam/x5dP_LATE_R2_S12.sort.dedup.bam     30559820      30559820
/home/mfaleeva/ARTDeco-master_3/bam/x5dD_LATE_R2_S11.sort.dedup.bam     20323589      20323589
 /home/mfaleeva/ARTDeco-master_3/bam/x5ND_LATE_R1_S1.sort.dedup.bam     15258988      15258988
 /home/mfaleeva/ARTDeco-master_3/bam/x5ND_LATE_R2_S9.sort.dedup.bam     22254209      22254209
 /home/mfaleeva/ARTDeco-master_3/bam/x5dD_LATE_R1_S3.sort.dedup.bam     20609729      20609729
Generating gene expression files...
Traceback (most recent call last):
  File "/home/mfaleeva/.conda/envs/artdeco/bin/ARTDeco", line 33, in <module>
    sys.exit(load_entry_point('ARTDeco==0.4', 'console_scripts', 'ARTDeco')())
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/main.py", line 472, in main
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/readthrough.py", line 59, in get_multi_gene_exp
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/ARTDeco-0.4-py3.10.egg/ARTDeco/readthrough.py", line 59, in <lambda>
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 707, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/mfaleeva/.conda/envs/artdeco/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1340, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat
```

All the preprocessing files have been generated without any problem. Any suggestions? (My apologies for the frequent queries, its my first time working in conda, I really appreciate your help).

**Comment by faleevz** [comment]
Re-installed artdeco and re-ran code, strangely fixed itself.
